master_build:
 stage: test
 script:
  - mvn clean deploy sonar:sonar
 tags:
  - java8
 only:
  - master

feature_build:
 stage: test
 script:
  - mvn clean verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
 tags:
  - java8