language: java

master_build:
 stage: test
 script:
  - mvn deploy sonar:sonar
 after_success:
  - coveralls
 only:
  - master

feature_build:
 stage: test
 script:
  - mvn verify sonar:sonar -Dsonar.analysis.mode=preview
 after_success:
  - coveralls
 except:
  - master