language: java
jdk: oraclejdk8
sudo: false

install: true
script:
- mvn clean install
after_success:
- mvn cobertura:cobertura
- bash <(curl -s https://codecov.io/bash)
cache:
 directories:
 - $HOME/.m2